### ISSUE TITLE
Mounting volume from sunodo bin directory is rejected by Docker

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#246]
## 🙂 Expected behavior

During `sunodo run` we now mount a docker compose volume in the path of the sunodo binary installation.
Sunodo run should always work.

## 🫠 Actual behavior

Docker requires that the directory is the white list of the directories that can be mounted.
Which is my case was not, raising the following error:

```
Error response from daemon: Mounts denied: 
The path /opt/homebrew/Cellar/sunodo/0.9.0/libexec/lib/node_modules/@sunodo/cli/dist/node/traefik is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
```

## 🧪 Minimal test case

Run `sunodo run` in a machine that doesn't have the sunodo bin dir in the while list.

## 🌎 Environment

macOS
Sunodo 0.9
Docker Desktop

## ✔️ Possible solutions

Setting up Docker to add the sunodo bin directory work.
But we should study a way to not need to map that volume

**Comment by oap75** [comment]
By default the `/Users`, `/Volume`, `/private`, `/tmp` and `/var/folders` directory are shared. If the project is outside these directories then it must be added to the list, otherwise you may get Mounts denied or cannot start service errors at runtime.

So, I think we can just put the `/tmp` directory inside the file-sharing via GUI or add below via command line to the file `~/Library/Group Containers/group.com.docker/settings.json`: 

```
"filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/private",
    "/tmp"
  ]
```

https://docs.docker.com/desktop/settings/mac/#file-sharing

https://github.com/docker/for-mac/issues/2214

**Comment by tuler** [comment]
The best would be to not need to mount any volumes. We are mounting now because of the traefik configuration, but traefik has other ways to configure, like using command line args.

**Comment by oap75** [comment]
> The best would be to not need to mount any volumes. We are mounting now because of the traefik configuration, but traefik has other ways to configure, like using command line args.

I'll investigate the traefik options then.

**Comment by oap75** [comment]
We can use `docker providers` along with `compose labels`. finally we can remove the volume.

**Comment by oap75** [comment]
We should fix it in two services : 

- [ ] 1 - Traefik 
- [ ] 2 - prompt
