### ISSUE TITLE
Get the user image tag in sunodo build command

### ISSUE THREAD

**Issue by oap75** [sunodo/sunodo#446]
## 📚 Context

The `build` sub-command creates docker image and finally generate a `sha256 hash` for it. So, it's not user friendly. specially when a user wants to create multiple versions.

## ✔️ Solution

The `build` sub-command can get a tag from user via command line and then create the docker image based on it. 

## 📈 Subtasks

-   [x] add an option to build command for user to set a tag

## 🎯 Definition of Done

-   [x] create a user friendly docker image name based on inputs.

**Comment by endersonmaia** [comment]
I didn't get the goal here. 

What's the use case for having a "user friendly" container image name for the result of the `sunodo build`?

AFAIK, it's used only to generate the EXT2 rootfs so that `cartesi-machine` can create the snapshot; there's no use case for `docker container run sha256:deadbeef...` for ex.

**Comment by oap75** [comment]
> I didn't get the goal here.
> 
> What's the use case for having a "user friendly" container image name for the result of the `sunodo build`?

I thought of situations where developers want to create multiple versions of their application. So, it's better for them to add names and versions for each build to distinguish the history afterward.

**Comment by endersonmaia** [comment]
Still on this, using the `sha256:...` gives us the hint about the (un)reproducibility of the build, since a different container image hash should give a different cartesi machine templateHash. 

One use case where I see the usage of having a container image is to embed the machine snapshot into the `cartesi/rollups-node image` and have the validator node for that dapp ready to be used/published.

In that case, I'd advocate to using the templateHash of the cartesi machine as the tag.

Something like `enderson/my-dapp:6ad235aa329beab5c1c48a50b4404299e120ee165de76bd21b0171b02b5880e7` where the output of `sunodo hash` would be `0x6ad235aa329beab5c1c48a50b4404299e120ee165de76bd21b0171b02b5880e7`

That would not require a `--tag` argument, though.

**Comment by endersonmaia** [comment]
> I thought of situations where developers want to create multiple versions of their application. So, it's better for them to add names and versions for each build to distinguish the history afterward.

> I thought of situations where developers want to create multiple versions of their application. So, it's better for them to add names and versions for each build to distinguish the history afterward.

The versions of the application could be managed by the underlying VCS (git, ...) with tags, branches and such.

Even if one could define a `--tag` (like the linked PR), we'd still need a way to recover from that tag to build the machine snapshot, right?

**Comment by endersonmaia** [comment]
> So, U meant the issue and the related PR is useless and should be closed ?

I mean I don't see a concrete use case for the issue described here.

And if I was going to review the PR, I'd say it's incomplete, since even if I define a `--tag`, the tag has no use for subsequent calls do `sunodo build` or `sunodo run`.
