### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#48]
## 📚 Context

There are several components involved in the development of DApps, each with their own versions:

We have [machine-emulator:0.14.0](https://github.com/cartesi/machine-emulator/releases/tag/v0.14.0) and [machine-emulator-tools:0.11.0](https://github.com/cartesi/machine-emulator-tools/releases/tag/v0.11.0), both are part of [machine-emulator-sdk:0.15.0](https://github.com/cartesi/machine-emulator-sdk/releases/tag/v0.15.0). On top of that we have [server-manager:0.7.0](https://github.com/cartesi/server-manager/releases/tag/v0.7.0).

Then we have cartesi rollups 0.9.0 framework, with several different Docker images, all with the same version, but with a strict compatibility with the emulator, and external APIs for GraphQL and Smart Contracts.

The DApp developer needs to deal with some of these versions. The `machine-emulator-tools` must be part of the application cartesi machine. The frontend uses the GraphQL and Smart Contracts APIs. The node, running locally for testing, must use the correct version.

For the end-user, the DApp developer, it's very hard, or impossible, to keep track of all these versions and compatibility.

## ✔️ Solution

One alternative is to build a compatibility matrix between all components. And try to allow mix and match different components versions.

For example allow a backend built with emulator 0.14.0 to be executed by a node 0.11.0.

The other alternative is to create a "Sunodo SDK" version, that binds together Emulador SDK version and Rollups version.

**Comment by edubart** [comment]
> For the end-user, the DApp developer, it's very hard, or impossible, to keep track of all these versions and compatibility.
> One alternative is to build a compatibility matrix between all components. And try to allow mix and match different components versions.

I think all components should start checking their Cartesi dependencies version, to ensure compatibility, otherwise a friendly error message must be raised to the user. For example, if Rollups v0.9.0 depends on Emulator v0.14.x, it should check that emulator is 0.14.x, otherwise raise an error. If there are a lot of components to be checked, it could have a versioning file (such as `package.json` for npm).

Following semver specifications, we should usually assume that any patch release (`x.y.z` where only `z` changes) maintains compatibility. While a feature release (`x.y.z` where `y` changes) or a major release, may not be compatible.

In the end, we need somehow to be able to configure a cascade of dependency versioning, with its dependencies versions being checked at runtime by every major component, this way we could make sure the components are compatible with each other and raise friendly error messages otherwise.

**Comment by tuler** [comment]
Versioning is being resolved in the SDK Docker image level.
